### ISSUE TITLE
Dynobench on pip

### ISSUE THREAD

**Issue by whoenig** [quimortiz/dynobench#9]
It would be great to have dynobench installable via pip. Moreover, the name of the Python module should also be changed to dynobench (currently `robot_python`).

Use case: I would like to use it as dynamics backend for our simulator in Crazyswarm2. (tagging @Khaledwahba1994 for visibility).

**Comment by quimortiz** [comment]
Ok! I will do it before the end of the month (I already did python bindings for dynotree, it should be easy)

**Comment by quimortiz** [comment]
What is the status of this issue? I can try to make a pip package.

**Comment by whoenig** [comment]
We were hoping you would be able to copy the infrastructure from dynotree for pip releases.

**Comment by quimortiz** [comment]
ok, will do it before I leave the lab

**Comment by whoenig** [comment]
Cool! I get:
```
python3 -c 'import dynobench; import numpy as np; print(dynobench.robot_factory(dynobench.PKGDIR + "models/unicycle1_v0.yaml", [], []).stepOut(np.zeros(3), np.ones(2),.1))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'dynobench' has no attribute 'PKGDIR'

```

**Comment by quimortiz** [comment]
strange, it works for me.  Can you check which version did you install? I have 0.0.2

**Comment by whoenig** [comment]
Works now - I had 0.0.1 in the cache.

**Comment by Khaledwahba1994** [comment]
Works for me.
